name : CI Pipeline

on : push

jobs : 
  project-testing:
    runs-on: ubuntu-latest

    steps:
     - name : checkout code
       uses : actions/checkout@v3

     - name : setup python
       uses : actions/setup-python@v2
       with : 
        python-version : '3.10'

     - name : Cache pip dependencies
       uses : actions/cache@v3
       with :
        path : ~/.cache/pip
        key : ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys : |
            ${{ runner.os }}-pip-

     - name : install dependencies
       run : |
          pip install -r requirements.txt

     - name : run pipeline
       env: 
        AKSHAT : ${{ secrets.AKSHAT }}
       run : |
          dvc repro
     
     - name : run test
       env :
        AKSHAT : ${{ secrets.AKSHAT }}
       run: |
          python -m unittest tests/test_model.py
     
     - name : promote model to production
       if : success()
       env : 
        AKSHAT : ${{ secrets.AKSHAT }}
       run : |
        python scripts/promote_model.py
     
     - name : run flask app tests
       if : success()
       env :
        AKSHAT : ${{ secrets.AKSHAT }}
       run : |
          python -m unittest tests/test_flask.py